Pull request fin de séance
CACAO-2023/CACAO-2023 pull request #42
Opened 2023-04-05 10:14 UTC by Dahan13

2023-04-05 11:04 UTC, massimotisi requested changes
You are changing files outside of your java package. You can see the files that you are changing in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.

You can replace these files with the version from the main repository. To do that, right click on these files or folders -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository (not your team repository) -> Replace. Then commit and push to your repository. Don't close the pull request, it will be automatically updated.

2023-04-06 08:24 UTC, massimotisi approved these changes

2023-04-06 08:29 UTC, Dahan13 commented
> You are changing files outside of your java package. You can see the files that you are changing in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.
> 
> You can replace these files with the version from the main repository. To do that, right click on these files or folders -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository (not your team repository) -> Replace. Then commit and push to your repository. Don't close the pull request, it will be automatically updated.

Problem is fixed now.

2023-04-06 08:30 UTC, massimotisi commented
Yes, but you need to fix also another problem. Your team repository is not up-to-date with the changes that happened on the main repository. Please pull from the main repository and then push to the team repository.

2023-04-12 06:41 UTC, merged